### ISSUE TITLE
Problem Set 1

### ISSUE THREAD

**Issue by camjwright** [camjwright/qss20_s21_assignments#1]

**Comment by camjwright** [comment]
[pset1_individualexercises_Cameron-Wright.pdf](https://github.com/camjwright/qss20_s21_assignments/files/6371153/pset1_individualexercises_Cameron-Wright.pdf)

**Comment by camjwright** [comment]
I'm not sure why I can't upload an ipynb to the issue but it's in the repository!

**Comment by rebeccajohnson88** [comment]
looks good! joined the repo
